import 'package:flutter/material.dart';
final ThemeData SpreadLight = new ThemeData(
  backgroundColor: Color(0xfff1f1f1),
  brightness: Brightness.light,
  scaffoldBackgroundColor: Color(0xfff1f1f1),
  secondaryHeaderColor: Color(0xffd2d2d2),
  primarySwatch: Colors.blue,
  primaryColor: Color(0xfff1f1f1),
  primaryColorBrightness: Brightness.light,
  accentColor: Colors.blue,
  primaryTextTheme: TextTheme(title: TextStyle(color:Colors.black,fontFamily: 'MontSerrat')),
  accentColorBrightness: Brightness.light,
  splashColor: Colors.blue,
  iconTheme: IconThemeData(color: Colors.black),
  textSelectionColor: Colors.blue,
);
final ThemeData SpreadDark = new ThemeData(
  backgroundColor: Color(0xff212121),
  secondaryHeaderColor: Colors.black38,
  brightness: Brightness.dark,
  primarySwatch: Colors.blue,
  primaryColor: Color(0xff1e1e1e),
  primaryColorBrightness: Brightness.dark,
  accentColor: Colors.blue,
  accentColorBrightness: Brightness.dark,
  splashColor: Colors.blue[300],
  primaryTextTheme: TextTheme(title: TextStyle(color:Colors.white,fontFamily: 'MontSerrat')),
  iconTheme: IconThemeData(color: Colors.white30),
  textSelectionColor: Colors.blue,
);  
